.include "m328pdef.inc"

.DEF TENSION_LEIDA = R16
.DEF TENSION_INICIAL = R17
.DEF REG_VACIO = R19
.DEF TEMP = R20
.DEF TIEMPO_ARRIBA_H = R21
.DEF TIEMPO_ARRIBA_L = R22
.DEF TIEMPO_TOTAL_H = R23
.DEF TIEMPO_TOTAL_L = R24
.DEF TEMP_H = R25
.DEF TEMP_L = R26

.CSEG
	RJMP MAIN

.EQU MASK_LECTURA_TENSION = 0xFF
.EQU PENDIENTE = 10
.EQU ORDENADA_ORIGEN = 25

.ORG 0x1C;INTERRUPCION POR TIM0_COMPA
	RJMP ISR_TIMER0_COMPA

.ORG INT_VECTORS_SIZE

MAIN:
;INICIALIZACION STACK
	LDI TEMP,HIGH(RAMEND)
	OUT SPH,TEMP
	LDI TEMP,LOW(RAMEND)
	OUT SPL,R16
;[FIN]INICIALIZACION STACK

;SETEO EL PUERTO C DE SALIDA
	LDI TEMP,DDRC
	ORI TEMP,MASK_LECTURA_TENSION
	OUT DDRC,TEMP
;[FIN]SETEO EL PUERTO C DE SALIDA

;SETEO CONTADOR
	LDS TEMP,TCCR1A
	ANDI TEMP,0x00
	STS TCCR1A,TEMP

	LDI TEMP,0x02;PRESCALEO EL TIMER
	STS TCCR1B,TEMP;PRESCALEO EL TIMER

	LDI TEMP,0x02;SETEO PARA QUE EL CONTADOR DEL TIMER SE IGUALE CON 0xFF
	STS TIMSK1,TEMP;SETEO PARA QUE EL CONTADOR DEL TIMER SE IGUALE CON 0xFF

	SEI
;[FIN]SETEO CONTADOR

;INICIALIZACION DE VARIABLES
	CLR REG_VACIO
	CLR TIEMPO_ARRIBA_H
	CLR TIEMPO_ARRIBA_L
	CLR TIEMPO_TOTAL_H
	CLR TIEMPO_TOTAL_L
	CALL OBTENER_TIEMPO_DESFASAJE
;[FIN]INICIALIZACION DE VARIABLES

HERE:RJMP HERE

OBTENER_TIEMPO_DESFASAJE:
ESPERAR_PARA_ARRANCAR:
	IN TENSION_INICIAL,PORTC;LEO TENSION INICIAL DEL ADC
LOOP_HASTA_ARRANCAR:
	IN TENSION_LEIDA,PORTC;LEO TENSION DEL ADC
	CP TENSION_INICIAL,TENSION_LEIDA;CHEQUEO SI HUBO UN CAMBIO DE ESTADO
	BREQ LOOP_HASTA_ARRANCAR;SI NO HUBO UN CAMBIO DE ESTADO, SIGO LEYENDO HASTA QUE PASE 
	
INIT_LEER_PULSO:
	LDI TEMP,0x00;LLEVO EL CONTADOR A 0
	STS TCNT1H,TEMP;LLEVO EL CONTADOR A 0
	STS TCNT1L,TEMP;LLEVO EL CONTADOR A 0
	MOV TENSION_INICIAL,TENSION_LEIDA;GUARDO LA TENSION INICIAL PARA LUEGO COMPARAR

LEER_PULSO:
	IN TENSION_LEIDA,PORTC;LEO TENSION DEL ADC
	CP TENSION_INICIAL,TENSION_LEIDA;CHEQUEO SI HUBO UN CAMBIO DE ESTADO
	BREQ LEER_PULSO;SI NO HUBO UN CAMBIO DE ESTADO, SIGO LEYENDO HASTA QUE PASE

VERIFICAR_ESTADO:;SI HUBO UN CAMBIO DE ESTADO, VERIFICO SI ESTOY EN LA PRIMERA O SEGUNDA PARTE DEL PERIODO
	LDS TEMP_H,TCNT1H;GUARDO EL VALOR ACTUAL DEL CONTADOR
	LDS TEMP_L,TCNT1H;GUARDO EL VALOR ACTUAL DEL CONTADOR
	CPI TIEMPO_ARRIBA_L,0;CHEQUEO SI YA PASE LA PRIMERA PARTE DEL PERIODO VERIFICANDO SI LLENE ESTE VARIABLE
	BREQ PASAJE_PRIMER_A_SEGUNDO_ESTADO;SI ESTA VACIO, PASO A GUARDAR EL TIEMPO DEL PRIMER ESTADO
	
AJUSTAR_TIEMPO_HIGH:
	CPI TENSION_INICIAL,0;VERIFICO SI LA TENSION INICIAL FUE LA TENSION HIGH
	BREQ FIN;SI LO FUE, PASO A CALCULAR LOS TIEMPOS
;	MOV TIEMPO_ARRIBA,TEMP;SI NO LO FUE, ENTONCES EL TIEMPO EN HIGH ERA EL DEL SEGUNDO ESTADO
	MOV TIEMPO_ARRIBA_H,TEMP_H;GUARDO EL TIEMPO DEL PRIMER ESTADO
	MOV TIEMPO_ARRIBA_L,TEMP_L;GUARDO EL TIEMPO DEL PRIMER ESTADO
FIN:RET

PASAJE_PRIMER_A_SEGUNDO_ESTADO:
	MOV TIEMPO_ARRIBA_H,TEMP_H;GUARDO EL TIEMPO DEL PRIMER ESTADO
	MOV TIEMPO_ARRIBA_L,TEMP_L;GUARDO EL TIEMPO DEL PRIMER ESTADO
	RJMP INIT_LEER_PULSO;VUELVO A COMENZAR LA LECTURA DEL ESTADO


ISR_TIMER0_COMPA:
	LDI TEMP,0x00;LLEVO EL CONTADOR A 0
	STS TCNT1H,TEMP
	STS TCNT1L,TEMP
RETI
