.include "m328pdef.inc"

.DSEG
.ORG SRAM_START

.DEF TEMP = R17
.DEF TIEMPO_ARRIBA_H = R18
.DEF TIEMPO_ARRIBA_L = R19
.DEF TIEMPO_TOTAL_H = R20
.DEF TIEMPO_TOTAL_L = R21

.CSEG
	RJMP MAIN
.ORG PCI1addr
	RJMP HANDLER_PC

.EQU MASK_LECTURA_TENSION = 0xFF
.EQU PENDIENTE = 10
.EQU ORDENADA_ORIGEN = 25

.ORG INT_VECTORS_SIZE

MAIN:
;INICIALIZACION STACK
	LDI TEMP,HIGH(RAMEND)
	OUT SPH,TEMP
	LDI TEMP,LOW(RAMEND)
	OUT SPL,TEMP
;[FIN]INICIALIZACION STACK

;SETEO EL PUERTO C DE SALIDA
	LDI TEMP,DDRC
	ORI TEMP,MASK_LECTURA_TENSION
	OUT DDRC,TEMP
;[FIN]SETEO EL PUERTO C DE SALIDA

;HABILITO LA INTERRUPCION POR PIN 6 DEL PUERTO C
	LDS TEMP,PCMSK1
	ORI TEMP,1<<PCINT14
	STS PCMSK1,TEMP
;[FIN]HABILITO LA INT1

;HABILITO LA INTERRUPCION POR PUERTO C
	LDS TEMP,PCICR
	ORI TEMP,(1<<PCIE1)
	STS PCICR,TEMP
;[FIN]HABILITO LA INTERRUPCION POR PUERTO C

;HABILITO INTERRUPCION
	SEI
;[FIN]HABILITO INTERRUPCION

;INICIALIZACION DE VARIABLES
	CLR TIEMPO_ARRIBA_H
	CLR TIEMPO_ARRIBA_L
	CLR TIEMPO_TOTAL_H
	CLR TIEMPO_TOTAL_L
	RCALL OBTENER_TIEMPO_DESFASAJE
;[FIN]INICIALIZACION DE VARIABLES

;HERE:RJMP HERE

OBTENER_TIEMPO_DESFASAJE:
HERE:RJMP HERE

SET_TIMER1:
	LDS TEMP,TCCR1A;SETEO PARA QUE EL TIMER CUENTE LO MAS QUE PUEDA
	ANDI TEMP,0x00;SETEO PARA QUE EL TIMER CUENTE LO MAS QUE PUEDA
	STS TCCR1A,TEMP;SETEO PARA QUE EL TIMER CUENTE LO MAS QUE PUEDA

	LDI TEMP,0x02;PRESCALEO Y PRENDO EL TIMER
	STS TCCR1B,TEMP;PRESCALEO Y PRENDO EL TIMER
RETI

UNSET_TIMER1:
	LDI TEMP,0x00;APAGO EL TIMER
	STS TCCR1B,TEMP;APAGO EL TIMER
RET

HANDLER_PC_HIGH:
	LDS TIEMPO_TOTAL_H,TCNT1H;GUARDO EL BYTE ALTO DEL TIMER
	LDS TIEMPO_TOTAL_L,TCNT1L;GUARDO EL BYTE BAJO DEL TIMER
	CPI TIEMPO_TOTAL_H,0;REVISO SI EL BYTE ALTO ES NULO
	BRNE UNSET_TIMER1;SI EL TIMER NO ES NULO, SIGNIFICA QUE YA CONTE LO QUE TENIA QUE CONTAR, POR LO CUAL DEJO DE CONTAR APAGANDO EL TIMER
	CPI TIEMPO_TOTAL_L,0;REVISO SI EL BYTE BAJO ES NULO
	BRNE UNSET_TIMER1;SI EL TIMER NO ES NULO, SIGNIFICA QUE YA CONTE LO QUE TENIA QUE CONTAR, POR LO CUAL DEJO DE CONTAR APAGANDO EL TIMER
	RJMP SET_TIMER1;SI EL TIMER ES NULO, PROCEDO A EMPEZAR A CONTAR SETEANDO EL TIMER

HANDLER_PC_LOW:
	LDS TIEMPO_ARRIBA_H,TCNT1H;GUARDO EL BYTE ALTO DEL TIMER
	LDS TIEMPO_ARRIBA_L,TCNT1L;GUARDO EL BYTE BAJO DEL TIMER
RETI

;HANDLER DE LA INTERRUPCION DEL PUERTO C
HANDLER_PC:
	SBIC PORTC,6;REVISO EL ESTADO DEL PUERTO C
	RJMP HANDLER_PC_HIGH;SI EL PUERTO C PASO A ESTAR ARRIBA PASO A REVISAR SI EL TIMER ESTABA PRENDIDO
	RJMP HANDLER_PC_LOW;SI EL PUERTO C PASO A ESTAR ABAJO PASO A REVISAR SI EL TIMER ESTABA PRENDIDO
