.include "m328pdef.inc"

.DEF TENSION_LEIDA = R16
.DEF CORRIENTE_LEIDA_HIGH = R17
.DEF CORRIENTE_LEIDA_LOW = R18
.DEF REG_VACIO = R19
.DEF TEMP = R20

.DSEG
TABLA_CORRIENTE:.BYTE 256

.CSEG
	RJMP MAIN

.EQU MASK_LECTURA_TENSION = 0xFF
.EQU PENDIENTE = 10
.EQU ORDENADA_ORIGEN = 25

.ORG INT_VECTORS_SIZE

MAIN:
;INICIALIZACION STACK
	LDI TEMP,HIGH(RAMEND)
	OUT SPH,TEMP
	LDI TEMP,LOW(RAMEND)
	OUT SPL,R16
;[FIN]INICIALIZACION STACK

;LEVANTAR DIRECCION DE LA TABLA DE CORRIENTE
	LDI XH,HIGH(TABLA_CORRIENTE)
	LDI XL,LOW(TABLA_CORRIENTE)
;[FIN]LEVANTAR DIRECCION DE LA TABLA DE CORRIENTE

;SETEO EL PUERTO C DE SALIDA
	LDI TEMP,DDRC
	ORI TEMP,MASK_LECTURA_TENSION
	OUT DDRC,TEMP
;[FIN]SETEO EL PUERTO C DE SALIDA

	CLR REG_VACIO
	CALL LEER_TENSION
	
HERE:RJMP HERE

LEER_TENSION:
	IN TENSION_LEIDA,PORTC;LEO TENSION DEL ADC

	;BUSCO HACER I = (M*V-I0)/2
	LDI TEMP,PENDIENTE
	
	;M*V
	MUL TENSION_LEIDA,TEMP
	MOV CORRIENTE_LEIDA_LOW,R0
	MOV CORRIENTE_LEIDA_HIGH,R1
	;[FIN]M*V

	;M*V-I0
	SUBI CORRIENTE_LEIDA_LOW,ORDENADA_ORIGEN
	SBC CORRIENTE_LEIDA_HIGH,REG_VACIO
	;[FIN]M*V-I0
	
	;(M*V-I0)/2
	LSR CORRIENTE_LEIDA_HIGH
	ROR CORRIENTE_LEIDA_LOW
	;[FIN](M*V-I0)/2
	
	;GUARDO VALOR EN LA TABLA DE CORRIENTE
	ST X+,CORRIENTE_LEIDA_HIGH
	ST X+,CORRIENTE_LEIDA_LOW
	;[FIN]GUARDO VALOR EN LA TABLA DE CORRIENTE

RJMP LEER_TENSION
